language: java

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - secure: ${COVERALLS_REPO_TOKEN}

jobs:
  include:
    - stage: Sonar check and code coverage reporting
      addons:
        sonarcloud:
          organization: "sadv1r-github"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - ./gradlew jacoco coveralls sonarqube