language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: Sonar check and code coverage reporting
      addons:
        sonarcloud:
          organization: "sadv1r-github"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - sudo apt-get install jq
        - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
        - ./gradlew test jacoco sonarqube
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml