language: java

jdk:
  - openjdk7
  - oraclejdk8

jobs:
  include:
    - stage: Sonar check and code coverage reporting
      addons:
        sonarcloud:
          organization: "sadv1r-github"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - ./gradlew cobertura coveralls sonarqube